# Generated by Django 4.1.3 on 2023-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='company/')),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='About_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='product/')),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_cost', models.IntegerField()),
                ('last_coat', models.IntegerField()),
                ('benefit', models.IntegerField()),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('website2', models.CharField(max_length=255)),
                ('website3', models.CharField(max_length=255)),
                ('website4', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product/')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='product/')),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='rec/')),
                ('text', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='background')),
                ('button', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Using',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
            ],
        ),
    ]
