# Generated by Django 4.1.3 on 2023-03-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_company',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
